#!/usr/bin/env python3
"""Build a founder/engineer candidate queue for Trajectory.

Sources:
1. Curated list of notable startup founders, engineers, and CS researchers
2. Wikipedia API category scraping for tech-related biographical categories
3. Filters against existing dataset to avoid duplicates

Outputs a candidate CSV and batch CSVs for subagent research.
"""
from __future__ import annotations
import argparse, csv, json, pathlib, random, time, urllib.parse, urllib.request
from collections import defaultdict

WIKI_API = "https://en.wikipedia.org/w/api.php"

# Curated seed list: (name, birth_year_or_None, category_hint)
CURATED = [
    # === Y Combinator founders ===
    ("Brian Chesky", 1981, "YC founder"),
    ("Joe Gebbia", 1981, "YC founder"),
    ("Nathan Blecharczyk", 1984, "YC founder"),
    ("Drew Houston", 1983, "YC founder"),
    ("Arash Ferdowsi", 1985, "YC founder"),
    ("Steve Huffman", 1983, "YC founder"),
    ("Alexis Ohanian", 1983, "YC founder"),
    ("Patrick Collison", 1988, "YC founder"),
    ("John Collison", 1990, "YC founder"),
    ("Brian Armstrong", 1983, "YC founder"),
    ("Tony Xu", 1985, "YC founder"),
    ("Andy Fang", 1990, "YC founder"),
    ("Stanley Tang", 1992, "YC founder"),
    ("Apoorva Mehta", 1986, "YC founder"),
    ("Kyle Vogt", 1985, "YC founder"),
    ("Emmett Shear", 1983, "YC founder"),
    ("Justin Kan", 1983, "YC founder"),
    ("Henrique Dubugras", 1996, "YC founder"),
    ("Pedro Franceschi", 1996, "YC founder"),
    ("Sid Sijbrandij", 1979, "YC founder"),
    ("Solomon Hykes", 1979, "YC founder"),
    ("Paul Graham", 1964, "YC founder"),
    ("Jessica Livingston", 1971, "YC founder"),
    ("Trevor Blackwell", 1969, "YC founder"),
    ("Robert Morris", 1965, "YC founder"),
    ("Sam Altman", 1985, "YC president"),
    ("Geoff Ralston", 1965, "YC partner"),
    ("Michael Seibel", 1982, "YC partner"),
    ("Aaron Harris", 1980, "YC partner"),
    ("Kat Manalac", None, "YC partner"),
    ("Kevin Hale", 1980, "YC partner"),
    ("Adora Cheung", None, "YC founder"),
    ("Lachy Groom", None, "YC partner"),
    ("Ali Rowghani", 1969, "YC partner"),
    ("Jared Friedman", 1984, "YC partner"),
    ("Dalton Caldwell", 1978, "YC partner"),
    ("Garry Tan", 1981, "YC president"),
    ("Paul Buchheit", 1977, "YC partner"),
    ("Harj Taggar", 1984, "YC partner"),
    ("Kirsty Nathoo", None, "YC partner"),
    ("Craig Cannon", None, "YC partner"),

    # === Major tech company founders ===
    ("Larry Page", 1973, "Google founder"),
    ("Sergey Brin", 1973, "Google founder"),
    ("Mark Zuckerberg", 1984, "Facebook founder"),
    ("Dustin Moskovitz", 1984, "Facebook founder"),
    ("Chris Hughes", 1983, "Facebook founder"),
    ("Andrew McCollum", 1984, "Facebook founder"),
    ("Eduardo Saverin", 1982, "Facebook founder"),
    ("Jack Dorsey", 1976, "Twitter founder"),
    ("Biz Stone", 1974, "Twitter founder"),
    ("Evan Williams", 1972, "Twitter founder"),
    ("Noah Glass", None, "Twitter founder"),
    ("Kevin Systrom", 1983, "Instagram founder"),
    ("Mike Krieger", 1986, "Instagram founder"),
    ("Jan Koum", 1970, "WhatsApp founder"),
    ("Brian Acton", 1972, "WhatsApp founder"),
    ("Evan Spiegel", 1990, "Snapchat founder"),
    ("Bobby Murphy", 1988, "Snapchat founder"),
    ("Reggie Brown", 1991, "Snapchat founder"),
    ("Daniel Ek", 1983, "Spotify founder"),
    ("Martin Lorentzon", 1969, "Spotify founder"),
    ("Reed Hastings", 1960, "Netflix founder"),
    ("Marc Randolph", 1958, "Netflix founder"),
    ("Jeff Bezos", 1964, "Amazon founder"),
    ("Elon Musk", 1971, "Tesla/SpaceX founder"),
    ("Kimbal Musk", 1972, "tech founder"),
    ("JB Straubel", 1975, "Tesla founder"),
    ("Ian Wright", None, "Tesla founder"),
    ("Marc Tarpenning", 1964, "Tesla founder"),
    ("Martin Eberhard", 1960, "Tesla founder"),
    ("Peter Thiel", 1967, "PayPal founder"),
    ("Max Levchin", 1975, "PayPal founder"),
    ("Ken Howery", 1977, "PayPal founder"),
    ("Luke Nosek", 1975, "PayPal founder"),
    ("Yu Pan", None, "PayPal founder"),
    ("Chad Hurley", 1977, "YouTube founder"),
    ("Steve Chen", 1978, "YouTube founder"),
    ("Jawed Karim", 1979, "YouTube founder"),
    ("Reid Hoffman", 1967, "LinkedIn founder"),
    ("Allen Blue", None, "LinkedIn founder"),
    ("Konstantin Guericke", None, "LinkedIn founder"),
    ("Eric Ly", None, "LinkedIn founder"),
    ("Jean-Luc Vaillant", None, "LinkedIn founder"),
    ("Ben Silbermann", 1982, "Pinterest founder"),
    ("Paul Sciarra", 1982, "Pinterest founder"),
    ("Evan Sharp", 1982, "Pinterest founder"),
    ("David Karp", 1986, "Tumblr founder"),
    ("Marco Arment", 1982, "Tumblr founder"),
    ("Alex Zhu", None, "Musical.ly founder"),
    ("Luyu Yang", None, "Musical.ly founder"),
    ("Shou Zi Chew", 1982, "TikTok CEO"),
    ("Zhang Yiming", 1983, "ByteDance founder"),
    ("Liang Rubo", None, "ByteDance founder"),
    ("Pavel Durov", 1984, "Telegram founder"),
    ("Nikolai Durov", 1980, "Telegram founder"),
    ("Brian Chesky", 1981, "Airbnb founder"),
    ("Adam D'Angelo", 1984, "Quora founder"),
    ("Charlie Cheever", 1981, "Quora founder"),
    ("Joshua Schachter", 1974, "Delicious founder"),
    ("Caterina Fake", 1969, "Flickr founder"),
    ("Stewart Butterfield", 1973, "Slack founder"),
    ("Cal Henderson", 1977, "Slack founder"),
    ("Sergio Villarreal", None, "Slack founder"),
    ("Eric Costano", None, "Slack founder"),
    ("Matt Mullenweg", 1984, "WordPress founder"),
    ("Mike Little", None, "WordPress founder"),
    ("DHH", 1979, "Rails creator"),
    ("Linus Torvalds", 1969, "Linux creator"),
    ("Guido van Rossum", 1956, "Python creator"),
    ("Brendan Eich", 1961, "JavaScript creator"),
    ("Yukihiro Matsumoto", 1965, "Ruby creator"),
    ("Rasmus Lerdorf", 1968, "PHP creator"),
    ("James Gosling", 1955, "Java creator"),
    ("Anders Hejlsberg", 1960, "C# creator"),
    ("Bjarne Stroustrup", 1950, "C++ creator"),
    ("Dennis Ritchie", 1941, "C creator"),
    ("Ken Thompson", 1943, "Unix creator"),
    ("Rob Pike", 1956, "Go creator"),
    ("Robert Griesemer", None, "Go creator"),
    ("Chris Lattner", 1978, "LLVM/Swift creator"),
    ("Joe Armstrong", 1950, "Erlang creator"),
    ("Jose Valim", 1985, "Elixir creator"),
    ("Evan You", 1987, "Vue.js creator"),
    ("Jordan Walke", None, "React creator"),
    ("Dan Abramov", 1986, "Redux creator"),
    ("Pete Hunt", None, "React engineer"),
    ("Tom Occhino", None, "React engineer"),
    ("Sindre Sorhus", 1987, "open source maintainer"),
    ("Feross Aboukhadijeh", 1992, "open source maintainer"),
    ("Sindre Sorhus", 1987, "open source maintainer"),
    ("Guillermo Rauch", 1986, "Vercel founder"),
    ("Nathan Rajlich", None, "open source maintainer"),
    ("Tim Caswell", None, "open source maintainer"),
    ("Isaac Schlueter", 1981, "npm creator"),
    ("Forrest Norvell", None, "npm engineer"),
    ("Charlie Robbins", None, "Node contributor"),
    ("Ryan Dahl", 1981, "Node.js creator"),
    ("Bert Belder", None, "Node.js contributor"),
    ("Ben Noordhuis", None, "Node.js contributor"),
    ("TJ Holowaychuk", 1987, "open source maintainer"),
    ("John Resig", 1984, "jQuery creator"),
    ("Sam Stephenson", None, "Prototype.js creator"),
    ("David Heinemeier Hansson", 1979, "Rails creator"),
    ("Jeremy Ashkenas", None, "CoffeeScript creator"),
    ("Misko Hevery", 1972, "Angular creator"),
    ("Evan You", 1987, "Vue creator"),
    ("Yehuda Katz", 1983, "Ember/Rails contributor"),
    ("Tom Dale", None, "Ember.js creator"),
    ("Leah Silber", None, "Ember.js contributor"),
    ("Godfrey Chan", None, "Rails contributor"),
    ("Aaron Patterson", 1978, "Rails/Ruby contributor"),
    ("Katherine Wu", None, "Rails contributor"),
    ("Eileen Uchitelle", None, "Rails contributor"),
    ("Sean Griffin", None, "Rails contributor"),
    ("Cristiano Betta", None, "tech engineer"),
    ("Kent Beck", 1961, "XP/TDD creator"),
    ("Martin Fowler", 1963, "software architect"),
    ("Robert C Martin", 1952, "Clean Code author"),
    ("Dave Thomas", None, "Pragmatic Programmer"),
    ("Andy Hunt", None, "Pragmatic Programmer"),
    ("Ward Cunningham", 1949, "wiki inventor"),
    ("Kent Beck", 1961, "TDD creator"),
    ("Ron Jeffries", None, "XP contributor"),
    ("Jeff Sutherland", 1941, "Scrum creator"),
    ("Ken Schwaber", None, "Scrum creator"),

    # === Notable engineers at major companies ===
    ("Jeff Dean", 1968, "Google engineer"),
    ("Sanjay Ghemawat", 1966, "Google engineer"),
    ("Bret Taylor", 1980, "Facebook CTO"),
    ("Mike Schroepfer", 1969, "Facebook CTO"),
    ("Andrew Bosworth", None, "Facebook VP"),
    ("Boz", None, "Facebook VP"),
    ("Chris Cox", 1982, "Facebook VP"),
    ("Ruchi Sanghvi", 1982, "Facebook engineer"),
    ("Jocelyn Goldfein", None, "Facebook engineer"),
    ("Meredith Chin", None, "Facebook engineer"),
    ("Scott Marlette", None, "Facebook engineer"),
    ("Aaron Sittig", None, "Facebook engineer"),
    ("Chris Putman", None, "Facebook engineer"),
    ("Matt Cohler", 1977, "Facebook VP"),
    ("Dave Morin", 1980, "Facebook engineer"),
    ("Chamath Palihapitiya", 1976, "Facebook VP"),
    ("Randi Zuckerberg", 1982, "Facebook marketing"),
    ("Naomi Gleit", None, "Facebook VP"),
    ("Kang-Xing Jin", None, "Facebook engineer"),
    ("Yishan Wong", None, "Facebook engineer"),
    ("Ethan Beard", None, "Facebook director"),
    ("Gokul Rajaram", None, "Facebook director"),
    ("Kate Losse", None, "Facebook engineer"),
    ("Ezra Callahan", None, "Facebook engineer"),
    ("Molly Graham", None, "Facebook comms"),
    ("Mark Pincus", 1966, "Zynga founder"),
    ("Andrew Trader", None, "Zynga founder"),
    ("Eric Schiermeyer", None, "Zynga founder"),
    ("Justin Waldron", None, "Zynga founder"),
    ("Steve Schoettler", None, "Zynga founder"),
    ("Amitt Mahajan", None, "Zynga engineer"),
    ("Kevin Chou", 1980, "Kabam founder"),
    ("Jeferson Nunez", None, "tech founder"),

    # === AI/ML researchers and founders ===
    ("Geoffrey Hinton", 1947, "AI researcher"),
    ("Yann LeCun", 1960, "AI researcher"),
    ("Yoshua Bengio", 1964, "AI researcher"),
    ("Andrew Ng", 1976, "AI researcher"),
    ("Ian Goodfellow", 1985, "AI researcher"),
    ("Andrej Karpathy", 1986, "AI researcher"),
    ("Dario Amodei", 1983, "Anthropic founder"),
    ("Daniela Amodei", 1986, "Anthropic founder"),
    ("Sam McCandlish", None, "Anthropic founder"),
    ("Tom Brown", 1991, "Anthropic founder"),
    ("Jack Clark", None, "Anthropic founder"),
    ("Jared Kaplan", None, "Anthropic founder"),
    ("Jonathan Uesato", None, "Anthropic researcher"),
    ("Aidan Gomez", 1995, "Cohere founder"),
    ("Nick Frosst", 1995, "Cohere founder"),
    ("Ivan Zhang", None, "Cohere founder"),
    ("Patrick Lewis", None, "Cohere researcher"),
    ("Douwe Kiela", 1988, "Cohere researcher"),
    ("Sara Hooker", None, "Cohere researcher"),
    ("Mistral AI founder", None, "AI founder"),
    ("Arthur Mensch", 1992, "Mistral AI founder"),
    ("Guillaume Lample", 1990, "Mistral AI founder"),
    ("Timothée Lacroix", None, "Mistral AI founder"),
    ("Clemens Delabrè", None, "Mistral AI founder"),
    ("Jean-Baptiste Alayrac", None, "AI researcher"),
    ("Lucas Beyer", None, "AI researcher"),
    ("Xiaohua Zhai", None, "AI researcher"),
    ("Alexey Dosovitskiy", 1987, "AI researcher"),
    ("Ashish Vaswani", 1986, "AI researcher"),
    ("Noam Shazeer", 1979, "AI researcher"),
    ("Niki Parmar", None, "AI researcher"),
    ("Jakob Uszkoreit", 1986, "AI researcher"),
    ("Llion Jones", 1986, "AI researcher"),
    ("Aidan Gomez", 1995, "AI researcher"),
    ("Lukasz Kaiser", None, "AI researcher"),
    ("Illia Polosukhin", 1985, "AI researcher"),
    ("Illia Polosukhin", 1985, "NEAR founder"),
    ("Alexander Rush", None, "AI researcher"),
    ("Sebastian Ruder", None, "AI researcher"),
    ("Sebastian Raschka", 1991, "AI researcher"),
    ("Andrej Karpathy", 1986, "AI researcher"),
    ("Jeremy Howard", 1971, "fast.ai founder"),
    ("Rachel Thomas", None, "fast.ai founder"),
    ("Sylvain Gugger", None, "fast.ai researcher"),
    ("Hugo Bowne-Anderson", None, "data scientist"),
    ("Chip Huyen", 1990, "AI engineer"),
    ("Eugene Yan", None, "ML engineer"),
    ("Lilian Weng", None, "AI researcher"),
    ("Jay Alammar", None, "AI educator"),
    ("Maarten Grootendorst", None, "AI researcher"),
    ("Sasha Rush", None, "AI researcher"),
    ("Tianqi Chen", 1990, "MXNet/XGBoost creator"),
    ("Mu Li", None, "MXNet creator"),
    ("Alex Smola", 1970, "MXNet creator"),
    ("Bing Xu", None, "MXNet contributor"),
    ("Yi Zhang", None, "MXNet contributor"),
    ("Leon Bottou", 1965, "ML researcher"),
    ("Olivier Chapelle", None, "ML researcher"),
    ("Jason Weston", 1971, "ML researcher"),
    ("Ronan Collobert", None, "ML researcher"),
    ("Soumith Chintala", 1988, "PyTorch contributor"),
    ("Adam Paszke", 1995, "PyTorch creator"),
    ("Sam Gross", None, "PyTorch contributor"),
    ("Michael Chau", None, "PyTorch contributor"),
    ("Edward Yang", None, "PyTorch contributor"),
    ("Zach DeVito", None, "PyTorch contributor"),
    ("James Hensman", None, "ML researcher"),
    ("Alex Wiltschko", None, "ML researcher"),
    ("Erik Meijer", 1963, "Rx creator"),
    ("Simon Peyton Jones", 1958, "Haskell researcher"),
    ("Phil Wadler", 1956, "Haskell researcher"),
    ("Lennart Augustsson", None, "Haskell researcher"),
    ("John Hughes", None, "Haskell researcher"),
    ("Conal Elliott", None, "FRP creator"),
    ("Bartosz Milewski", 1958, "category theory"),
    ("Mikhail Bourtsev", None, "tech engineer"),

    # === Crypto/web3 founders ===
    ("Vitalik Buterin", 1994, "Ethereum founder"),
    ("Gavin Wood", 1980, "Ethereum/Polkadot founder"),
    ("Charles Hoskinson", 1987, "Cardano founder"),
    ("Joseph Lubin", 1964, "Ethereum founder"),
    ("Mihai Alisie", None, "Ethereum founder"),
    ("Anthony Di Iorio", 1974, "Ethereum founder"),
    ("Amir Chetrit", None, "Ethereum founder"),
    ("Jeffrey Wilcke", None, "Ethereum founder"),
    ("Lars Klawitter", None, "tech founder"),
    ("Dan Larimer", 1981, "EOS/Steem founder"),
    ("Jed McCaleb", 1975, "Ripple/Stellar founder"),
    ("Arthur Britto", None, "Ripple founder"),
    ("David Schwartz", 1964, "Ripple CTO"),
    ("Chris Larsen", 1960, "Ripple founder"),
    ("Brad Garlinghouse", 1968, "Ripple CEO"),
    ("Sam Bankman-Fried", 1992, "FTX founder"),
    ("Gary Wang", 1994, "FTX founder"),
    ("Nishad Singh", 1996, "FTX engineer"),
    ("Caroline Ellison", 1994, "Alameda CEO"),
    ("Kyle Davies", None, "3AC founder"),
    ("Su Zhu", 1987, "3AC founder"),
    ("Do Kwon", 1991, "Terra founder"),
    ("Shin Hyun-seong", None, "Terra founder"),
    ("Anatoly Yakovenko", 1978, "Solana founder"),
    ("Raj Gokal", None, "Solana founder"),
    ("Greg Fitzgerald", None, "Solana engineer"),
    ("Stephen Akridge", None, "Solana engineer"),
    ("Balaji Srinivasan", 1980, "crypto/tech founder"),
    ("Naval Ravikant", 1974, "AngelList founder"),
    ("Babak Nivi", None, "AngelList founder"),
    ("Kevin Laws", None, "AngelList founder"),
    ("Stanley Ching", None, "AngelList founder"),
    ("Sahil Lavingia", 1993, "Gumroad founder"),
    ("Daniel Gross", 1987, "AngelList/YC partner"),
    ("Dhani Olshefski", None, "tech founder"),

    # === Notable startup founders (various) ===
    ("Evan Piekaz", None, "tech founder"),
    ("Alexis Ohanian", 1983, "Reddit founder"),
    ("Aaron Swartz", 1986, "Reddit/RSS contributor"),
    ("Aaron Iba", None, "tech founder"),
    ("Sergey Brin", 1973, "Google founder"),
    ("Craig Silverstein", 1972, "Google first engineer"),
    ("Urs Holzle", None, "Google engineer"),
    ("Marissa Mayer", 1975, "Google VP"),
    ("Salar Kamangar", 1975, "Google VP"),
    ("Susan Wojcicki", 1968, "Google VP"),
    ("Anne E Schwartz", None, "Google engineer"),
    ("Shona Brown", None, "Google VP"),
    ("Stuart Feldman", None, "Google engineer"),
    ("Alan Eustace", 1954, "Google VP"),
    ("Ben Goodger", None, "Chrome engineer"),
    ("Darren Fisher", None, "Google engineer"),
    ("Brian Rakowski", None, "Chrome engineer"),
    ("Justin Schuh", None, "Chrome engineer"),
    ("Carlos Pizano", None, "Chrome engineer"),
    ("Tim Steele", None, "Chrome engineer"),
    ("Fadi Chehadé", 1962, "tech executive"),
    ("Brian Bershad", None, "Google engineer"),
    ("Jeremy Doig", None, "Google engineer"),
    ("Mike Belshe", 1972, "HTTP/2 author"),
    ("Roberto Peon", None, "Google engineer"),
    ("Adrian Bubalo", None, "Google engineer"),
    ("Walter Bright", 1958, "D language creator"),
    ("Andrei Alexandrescu", 1969, "D/C++ author"),
    ("Scott Meyers", 1959, "C++ author"),
    ("Herb Sutter", 1963, "C++ author"),
    ("Bjorn Karlsson", None, "C++ author"),
    ("Matthew Wilson", None, "C++ author"),
    ("Stephan Lavavej", None, "C++ library maintainer"),
    ("Marshall Clow", None, "C++ library maintainer"),
    ("Jonathan Wakely", None, "C++ library maintainer"),
    ("Daniel Krugler", None, "C++ library maintainer"),
    ("Nicolai Josuttis", 1958, "C++ author"),
    ("Howard Hinnant", None, "C++ library maintainer"),
    ("Eric Niebler", None, "C++/Rust contributor"),
    ("Sean Parent", None, "C++ engineer"),
    ("Fedor Pikus", None, "C++ engineer"),
    ("Boris Schaling", None, "C++ author"),
    ("Bartek Filipowicz", None, "C++ author"),
    ("Andreas Fertig", None, "C++ author"),
    ("Klaus Iglberger", None, "C++ author"),
    ("Rainer Grimm", None, "C++ author"),
    ("Gor Nishanov", None, "C++ contributor"),
    ("Gor Mitic", None, "tech engineer"),

    # === Open source maintainers ===
    ("Linus Torvalds", 1969, "Linux/Git creator"),
    ("Greg Kroah-Hartman", 1970, "Linux kernel maintainer"),
    ("Andrew Morton", 1959, "Linux kernel maintainer"),
    ("Ingo Molnar", 1973, "Linux kernel maintainer"),
    ("Theodore Ts'o", 1968, "Linux kernel maintainer"),
    ("Al Viro", None, "Linux kernel maintainer"),
    ("David Miller", None, "Linux kernel maintainer"),
    ("Stephen Rothwell", None, "Linux kernel maintainer"),
    ("Arnd Bergmann", None, "Linux kernel maintainer"),
    ("Geert Uytterhoeven", None, "Linux kernel maintainer"),
    ("Thomas Gleixner", None, "Linux kernel maintainer"),
    ("Peter Zijlstra", None, "Linux kernel maintainer"),
    ("Paul McKenney", 1948, "Linux kernel maintainer"),
    ("Jonathan Corbet", 1969, "LWN founder"),
    ("Lennart Poettering", 1980, "systemd creator"),
    ("Kay Sievers", 1980, "systemd contributor"),
    ("Harald Hoyer", None, "systemd contributor"),
    ("Tom Gundersen", None, "systemd contributor"),
    ("Zbigniew Jędrzejewski-Szmek", None, "systemd contributor"),
    ("Michal Schmidt", None, "systemd contributor"),
    ("Daniel Mack", None, "systemd contributor"),
    ("Sebastian Thorarensen", None, "tech engineer"),

    # === Notable CS researchers ===
    ("Donald Knuth", 1938, "CS researcher"),
    ("Edsger Dijkstra", 1930, "CS researcher"),
    ("Tony Hoare", 1934, "CS researcher"),
    ("Niklaus Wirth", 1934, "CS researcher"),
    ("Butler Lampson", 1943, "CS researcher"),
    ("Leslie Lamport", 1941, "CS researcher"),
    ("Barbara Liskov", 1939, "CS researcher"),
    ("John McCarthy", 1927, "AI pioneer"),
    ("Marvin Minsky", 1927, "AI pioneer"),
    ("Claude Shannon", 1916, "info theory"),
    ("Alan Kay", 1940, "OOP pioneer"),
    ("Douglas Engelbart", 1925, "mouse inventor"),
    ("Vint Cerf", 1943, "TCP/IP creator"),
    ("Bob Kahn", 1938, "TCP/IP creator"),
    ("Tim Berners-Lee", 1955, "WWW creator"),
    ("Robert Cailliau", 1947, "WWW contributor"),
    ("Marc Andreessen", 1971, "Netscape founder"),
    ("Eric Bina", 1964, "Netscape founder"),
    ("Jim Clark", 1944, "Netscape founder"),
    ("Sabeer Bhatia", 1968, "Hotmail founder"),
    ("Jack Smith", 1968, "Hotmail founder"),
    ("Pierre Omidyar", 1967, "eBay founder"),
    ("Meg Whitman", 1956, "eBay CEO"),
    ("Jeff Skoll", 1965, "eBay founder"),
    ("Steve Westly", 1957, "eBay VP"),
    ("Brian Maggi", None, "tech founder"),
    ("Max Levchin", 1975, "PayPal founder"),
    ("Jeremy Stoppelman", 1977, "Yelp founder"),
    ("Russel Simmons", 1979, "Yelp founder"),
    ("David Galbraith", None, "tech founder"),
    ("Yelp founder", None, "tech founder"),
    ("Premal Shah", None, "Kiva founder"),
    ("Matt Flannery", None, "Kiva founder"),
    ("Jessica Jackley", 1977, "Kiva founder"),
    ("Charles Best", 1976, "DonorsChoose founder"),
    ("Slava Akhmechet", None, "RethinkDB founder"),
    ("Michael Glukhovsky", None, "RethinkDB founder"),
    ("Henrik Ingo", None, "RethinkDB engineer"),
    ("Ryan Paul", None, "tech engineer"),
    ("Alexis Ohanian", 1983, "Reddit founder"),
    ("Steve Huffman", 1983, "Reddit founder"),
    ("Christopher Slowe", 1985, "Reddit engineer"),
    ("Keith Rabois", 1969, "tech investor"),
    ("Keith Schacht", None, "tech founder"),
    ("Fred Ehrsam", 1988, "Coinbase founder"),
    ("Olaf Carlson-Wee", 1989, "crypto founder"),
    ("Katherine Wu", None, "crypto engineer"),
    ("Linda Xie", None, "crypto founder"),
    ("Satoshi Nakamoto", None, "Bitcoin creator"),
    ("Hal Finney", 1956, "Bitcoin contributor"),
    ("Nick Szabo", 1964, "crypto pioneer"),
    ("Wei Dai", None, "crypto pioneer"),
    ("Adam Back", 1970, "Blockstream founder"),
    ("Greg Maxwell", None, "Bitcoin contributor"),
    ("Pieter Wuille", 1988, "Bitcoin contributor"),
    ("Peter Todd", 1980, "Bitcoin contributor"),
    ("Bryan Bishop", None, "Bitcoin contributor"),
    ("Cory Fields", None, "Bitcoin contributor"),
    ("Luke Dashjr", None, "Bitcoin contributor"),
    ("Matt Corallo", 1988, "Bitcoin contributor"),
    ("Jonas Schnelli", None, "Bitcoin contributor"),
    ("MarcoFalke", None, "Bitcoin contributor"),
    ("Sjors Provoost", None, "Bitcoin contributor"),
    ("James O'Beirne", None, "Bitcoin contributor"),
    ("John Newbery", None, "Bitcoin contributor"),
    ("Steve Lee", None, "Bitcoin contributor"),
    ("Tim Ruffing", None, "Bitcoin contributor"),
    ("Jonas Nick", None, "Bitcoin contributor"),
    ("Antoine Poinsot", None, "Bitcoin contributor"),

    # === Fintech founders ===
    ("Patrick Collison", 1988, "Stripe founder"),
    ("John Collison", 1990, "Stripe founder"),
    ("Greg Brockman", 1987, "Stripe CTO"),
    ("Christie Koehler", None, "Stripe engineer"),
    ("Zach Perret", 1986, "Plaid founder"),
    ("William Hockey", 1988, "Plaid founder"),
    ("Daniel Lopatto", None, "tech engineer"),
    ("Henrique Dubugras", 1996, "Brex founder"),
    ("Pedro Franceschi", 1996, "Brex founder"),
    ("Zachary Abrams", None, "Brex engineer"),
    ("Cristina Cordova", None, "Stripe VP"),
    ("Sahil Lavingia", 1993, "Gumroad founder"),
    ("Alexis Evans", None, "tech founder"),
    ("Max Metchett", None, "tech founder"),
    ("Jack Zhang", None, "tech founder"),
    ("Rohan Seth", 1991, "tech founder"),
    ("Alex Wang", 1997, "Scale AI founder"),
    ("Lucas Wang", None, "tech founder"),
    ("Greg Yang", None, "tech founder"),
    ("Alexandr Wang", 1997, "Scale AI founder"),
    ("Sam Altman", 1985, "OpenAI/Loopd founder"),
    ("Greg Brockman", 1987, "OpenAI founder"),
    ("Ilya Sutskever", 1985, "OpenAI founder"),
    ("Wojciech Zaremba", 1988, "OpenAI founder"),
    ("Elon Musk", 1971, "OpenAI founder"),
    ("Reid Hoffman", 1967, "OpenAI funder"),
    ("Peter Thiel", 1967, "OpenAI funder"),
    ("Jessica Livingston", 1971, "OpenAI funder"),
    ("Mira Murati", 1988, "OpenAI CTO"),
    ("Bob McGrew", None, "OpenAI VP"),
    ("Mark Chen", None, "OpenAI researcher"),
    ("Alec Radford", 1992, "OpenAI researcher"),
    ("Jeffrey Wu", None, "OpenAI researcher"),
    ("Hyung Won Chung", None, "OpenAI researcher"),
    ("Long Ouyang", None, "OpenAI researcher"),
    ("Ryan Teo", None, "OpenAI researcher"),
    ("Gaurav Misra", None, "OpenAI researcher"),
    ("Chelsea Voss", None, "OpenAI researcher"),
    ("Adina Williams", None, "OpenAI researcher"),
    ("Karina Nguyen", None, "OpenAI researcher"),
    ("Scott Gray", None, "OpenAI engineer"),
    ("Jacob Menick", None, "OpenAI researcher"),
    ("Aman Anand", None, "OpenAI engineer"),
    ("Arvind Neelakantan", None, "OpenAI engineer"),
    ("Jared Kaplan", None, "OpenAI researcher"),
    ("Szymon Sidor", None, "OpenAI engineer"),
    ("Rewon Child", None, "OpenAI researcher"),
    ("David Luan", None, "AI researcher"),
    ("Rafał Józefowicz", None, "OpenAI researcher"),
    ("Alex Ray", None, "OpenAI researcher"),
    ("Arun Vasudev", None, "OpenAI engineer"),
    ("Heather Miller", None, "tech engineer"),
    ("Dario Amodei", 1983, "Anthropic founder"),
    ("Daniela Amodei", 1986, "Anthropic founder"),
    ("Sam McCandlish", None, "Anthropic founder"),
    ("Tom Brown", 1991, "Anthropic founder"),
    ("Jack Clark", None, "Anthropic founder"),
    ("Jared Kaplan", None, "Anthropic founder"),
    ("Christopher Olah", 1990, "Anthropic researcher"),
    ("Amanda Askell", 1988, "Anthropic researcher"),
    ("Jan Leike", None, "AI researcher"),
    ("John Schulman", None, "Anthropic researcher"),
    ("Filipe de Avila Belbute Peres", None, "AI researcher"),
    ("Yuri Burda", None, "AI researcher"),
    ("Hugo Touvron", 1993, "AI researcher"),
    ("Thibaut Lavril", None, "AI researcher"),
    ("Gautier Izacard", None, "AI researcher"),
    ("Graham Berrigan", None, "AI researcher"),
    ("Timothée Lacroix", None, "AI researcher"),
    ("Guillaume Lample", 1990, "Mistral AI founder"),
    ("Arthur Mensch", 1992, "Mistral AI founder"),

    # === Notable engineers and inventors ===
    ("Nolan Bushnell", 1943, "Atari founder"),
    ("Ted Dabney", 1937, "Atari founder"),
    ("Larry Kaplan", None, "Atari engineer"),
    ("Steve Jobs", 1955, "Apple founder"),
    ("Steve Wozniak", 1950, "Apple founder"),
    ("Ronald Wayne", 1934, "Apple founder"),
    ("Bill Gates", 1955, "Microsoft founder"),
    ("Paul Allen", 1953, "Microsoft founder"),
    ("Steve Ballmer", 1956, "Microsoft CEO"),
    ("Jon Shirley", None, "Microsoft CEO"),
    ("Tandy Trower", None, "Microsoft engineer"),
    ("Charles Simonyi", 1948, "Microsoft engineer"),
    ("Ray Ozzie", 1955, "Microsoft CTO"),
    ("James Allchin", 1951, "Microsoft VP"),
    ("Brian Valentine", None, "Microsoft VP"),
    ("Chris Jones", None, "Microsoft VP"),
    ("Henry Gabryjelski", None, "Microsoft engineer"),
    ("Larry Osterman", None, "Microsoft engineer"),
    ("Raymond Chen", None, "Microsoft engineer"),
    ("Joel Spolsky", 1965, "Stack Overflow/Trello founder"),
    ("Michael Pryor", 1975, "Trello founder"),
    ("Jeff Atwood", 1970, "Discourse/Stack Overflow founder"),
    ("Sam Soffes", None, "tech engineer"),
    ("Marco Arment", 1982, "Instapaper/Overcast founder"),
    ("John Gruber", 1969, "Daring Fireball"),
    ("MG Siegler", None, "tech writer/VC"),
    ("Alexia Tsotsis", None, "tech writer"),
    ("Matthew Panzarino", None, "tech writer"),
    ("Darrell Etherington", None, "tech writer"),
    ("Romain Dillet", None, "tech writer"),
    ("Anthony Ha", None, "tech writer"),
    ("Sarah Perez", None, "tech writer"),
    ("Jordan Crook", None, "tech writer"),
    ("Leena Rao", None, "tech writer"),
    ("Kim Mai Cutler", None, "tech writer"),
    ("Alex Wilhelm", None, "tech writer"),
    ("Danny Crichton", None, "tech writer"),
    ("Devin Coldewey", None, "tech writer"),
    ("Frederic Lardinois", None, "tech writer"),
    ("Ron Miller", None, "tech writer"),
    ("Ingrid Lunden", None, "tech writer"),
    ("Mike Butcher", 1966, "tech writer"),
    ("Alex Woodie", None, "tech writer"),
    ("Timothy Prickett Morgan", None, "tech writer"),
    ("The Register writer", None, "tech writer"),

    # === Hardware/IoT founders ===
    ("Palm founder", None, "tech founder"),
    ("Jeff Hawkins", 1957, "Palm founder"),
    ("Donna Dubinsky", 1955, "Palm founder"),
    ("Ed Colligan", 1961, "Palm founder"),
    ("Tony Fadell", 1969, "Nest/iPhone engineer"),
    ("Matt Rogers", 1983, "Nest founder"),
    ("Ben Gordon", None, "tech founder"),
    ("Hugo Barra", 1976, "tech executive"),
    ("Andrew Ng", 1976, "Coursera founder"),
    ("Daphne Koller", 1968, "Coursera founder"),
    ("Sebastian Thrun", 1967, "Udacity founder"),
    ("Mike Sokolsky", None, "Udacity founder"),
    ("David Stavens", None, "Udacity founder"),
    ("Salman Khan", 1976, "Khan Academy founder"),
    ("Byju Raveendran", 1976, "Byju's founder"),
    ("Divya Gokulnath", None, "Byju's founder"),
    ("Erin Musk", None, "tech founder"),

    # === Game developers ===
    ("John Carmack", 1970, "id Software founder"),
    ("John Romero", 1967, "id Software founder"),
    ("Tom Hall", 1964, "id Software founder"),
    ("Adrian Carmack", 1969, "id Software founder"),
    ("Kevin Cloud", None, "id Software founder"),
    ("Todd Hollenshead", None, "id Software CEO"),
    ("Tim Sweeney", 1970, "Epic Games founder"),
    ("Mark Rein", 1963, "Epic Games VP"),
    ("Cliff Bleszinski", 1975, "Epic Games designer"),
    ("Gabe Newell", 1962, "Valve founder"),
    ("Mike Harrington", 1965, "Valve founder"),
    ("Robin Walker", None, "Valve engineer"),
    ("John Cook", None, "Valve engineer"),
    ("Yahn Bernier", None, "Valve engineer"),
    ("Jason Mitchell", None, "Valve engineer"),
    ("Kelly Thornton", None, "Valve engineer"),
    ("Matthew O'Dwyer", None, "Valve engineer"),
    ("Marcus Schwarting", None, "Valve engineer"),
    ("Randy Lundblad", None, "Valve engineer"),
    ("Kerry Davis", None, "Valve engineer"),
    ("Katie Ganski", None, "Valve engineer"),
    ("Notch", 1979, "Minecraft creator"),
    ("Markus Persson", 1979, "Minecraft creator"),
    ("Jens Bergensten", 1984, "Minecraft developer"),
    ("Daniel Kaplan", None, "Mojang founder"),
    ("Carl Manneh", None, "Mojang CEO"),
    ("Jakob Porsér", None, "Mojang founder"),
    (" Tobias Möllstam", None, "Mojang engineer"),
    ("Jeb_", 1984, "Minecraft developer"),
    ("Dinnerbone", None, "Minecraft developer"),
    ("Grumm", None, "Minecraft developer"),
    ("Nathan Adams", None, "Minecraft developer"),
    ("Erik Broes", None, "Minecraft developer"),
    ("Michael Stoyke", None, "Minecraft developer"),
    ("Searge", None, "Minecraft developer"),
    ("ProfMobius", None, "Minecraft developer"),
    ("Roi Feldman", None, "tech engineer"),

    # === Notable women in tech ===
    ("Ada Lovelace", 1815, "CS pioneer"),
    ("Grace Hopper", 1906, "COBOL creator"),
    ("Hedy Lamarr", 1914, "frequency hopping"),
    ("Katherine Johnson", 1918, "NASA mathematician"),
    ("Margaret Hamilton", 1936, "Apollo software"),
    ("Radia Perlman", 1951, "networking pioneer"),
    ("Anita Borg", 1949, "tech advocate"),
    ("Frances Allen", 1932, "compiler pioneer"),
    ("Jean Sammet", 1928, "COBOL contributor"),
    ("Karen Sparck Jones", 1935, "IR pioneer"),
    ("Wendy Hall", 1952, "web pioneer"),
    ("Wendy Schmidt", 1955, "tech philanthropist"),
    ("Sheryl Sandberg", 1969, "Facebook COO"),
    ("Marissa Mayer", 1975, "Google/Yahoo CEO"),
    ("Meg Whitman", 1956, "eBay/HPE CEO"),
    ("Ursula Burns", 1958, "Xerox CEO"),
    ("Ginni Rometty", 1957, "IBM CEO"),
    ("Safra Catz", 1961, "Oracle CEO"),
    ("Ruth Porat", 1957, "Google CFO"),
    ("Susan Wojcicki", 1968, "YouTube CEO"),
    ("Anne Wojcicki", 1973, "23andMe founder"),
    ("Janet Wojcicki", None, "tech adjacent"),
    ("Sara Wojcicki", None, "tech adjacent"),
    ("Jessica Powell", None, "Google comms"),
    ("Bethanye Blount", None, "tech engineer"),
    ("Tracy Chou", 1988, "Pinterest engineer"),
    ("Elena Silenok", None, "tech founder"),
    ("Sara Mauskopf", None, "tech founder"),
    ("Sahil Lavingia", 1993, "Gumroad founder"),
    ("Katherine Maher", 1983, "Wikimedia CEO"),
    ("Megan Garcia", None, "tech executive"),
    ("Reshma Saujani", 1975, "Girls Who Code founder"),
    ("Jewel Burks", None, "tech founder"),
    ("Brianne Garcia", None, "tech engineer"),
    ("Pooja Sankar", None, "Piazza founder"),
    ("Stephanie Hurlburt", None, "tech founder"),
    ("Brianna Wu", 1987, "game developer"),
    ("Zoe Quinn", 1987, "game developer"),
    ("Anita Sarkeesian", 1983, "media critic"),
    ("Adrienne Porter Felt", None, "Chrome engineer"),
    ("Parisa Tabriz", 1982, "Chrome security"),
    ("Pamela Fox", 1986, "tech engineer"),
    ("Estelle Weyl", None, "web developer"),
    ("Lea Verou", 1991, "web standards advocate"),
    ("Sara Soueidan", 1989, "web developer"),
    ("Una Kravets", 1990, "web developer"),
    ("Mano Marks", None, "Docker engineer"),
    ("Katherine Wu", None, "tech engineer"),
    ("Lara Schenk", None, "web developer"),
    ("Rachel Andrew", 1967, "web developer"),
    ("Jen Simmons", 1975, "web standards advocate"),
    ("Eric Meyer", 1967, "web standards advocate"),
    ("Meyer Epstein", None, "tech engineer"),

    # === Dev tools / infrastructure founders ===
    ("Sid Sijbrandij", 1979, "GitLab founder"),
    ("Dmitriy Zaporozhets", 1984, "GitLab founder"),
    ("Valery Sizov", None, "GitLab engineer"),
    ("Pavel Byles", None, "tech engineer"),
    ("Tom Preston-Werner", 1979, "GitHub founder"),
    ("Chris Wanstrath", 1985, "GitHub founder"),
    ("PJ Hyett", 1981, "GitHub founder"),
    ("Scott Chacon", 1982, "GitHub founder"),
    ("Cameron McEfee", None, "GitHub engineer"),
    ("Kyle Daigle", None, "GitHub engineer"),
    ("Heather Baldry", None, "GitHub engineer"),
    ("Ben Balter", 1987, "GitHub engineer"),
    ("John Britton", None, "GitHub engineer"),
    ("Mislav Marohnić", 1986, "GitHub engineer"),
    ("Tim Clem", None, "GitHub engineer"),
    ("Vicent Marti", None, "GitHub engineer"),
    ("Arthur Schreiber", None, "GitHub engineer"),
    ("Jesse Newland", None, "GitHub engineer"),
    ("Brent Beer", None, "GitHub engineer"),
    ("Andrew Hodges", None, "tech engineer"),
    ("Zach Holman", 1987, "GitHub engineer"),
    ("Wynn Netherland", None, "GitHub engineer"),
    ("Joel Watson", None, "GitHub engineer"),
    ("Brandon Keepers", None, "GitHub engineer"),
    ("Rob Sanheim", None, "GitHub engineer"),
    ("Nick Quaranto", None, "GitHub engineer"),
    ("Scott J Beck", None, "GitHub engineer"),
    ("Brian Leroux", 1979, "Adobe/PhoneGap engineer"),
    ("Brock Whitten", None, "PhoneGap founder"),
    ("Rob Ellis", None, "PhoneGap founder"),
    ("Fil Maj", None, "PhoneGap engineer"),
    ("Herm Wong", None, "PhoneGap engineer"),
    ("Michael Brooks", None, "PhoneGap engineer"),
    ("Steve Gill", None, "PhoneGap engineer"),
    ("Jesse MacFadyen", None, "PhoneGap engineer"),
    ("Drew Hamlin", None, "tech engineer"),
    ("James Pearce", None, "tech engineer"),
    ("Brian LeRoux", 1979, "tech engineer"),

    # === Cloud / infra founders ===
    ("Werner Vogels", 1958, "Amazon CTO"),
    ("Ben Black", None, "tech engineer"),
    ("Chris Pinkham", None, "AWS founder"),
    ("Benjamin Black", None, "AWS engineer"),
    ("Willem van Biljon", None, "AWS engineer"),
    ("Christophe Coenraets", None, "Adobe engineer"),
    ("James Watters", None, "tech engineer"),
    ("Solomon Hykes", 1979, "Docker founder"),
    ("Sebastiën Pahl", None, "Docker founder"),
    ("Andrea Luzzardi", None, "Docker engineer"),
    ("Jérôme Petazzoni", None, "Docker engineer"),
    ("Gordon Ting", None, "Docker engineer"),
    ("Derek McGowan", None, "Docker engineer"),
    ("Stephen Day", None, "Docker engineer"),
    ("Brian Goff", None, "Docker engineer"),
    ("Alex Larsson", None, "Docker engineer"),
    ("Antoine Cotten", None, "Docker engineer"),
    ("Tianon Gravi", None, "Docker engineer"),
    ("Aanand Prasad", None, "Docker engineer"),
    ("Nicolas De Loof", None, "Docker engineer"),
    ("Craig Tracey", None, "Docker engineer"),
    ("Ken Cochrane", None, "Docker engineer"),
    ("Matt Boersma", None, "Docker engineer"),
    ("Aaron Grattafiori", None, "Docker engineer"),
    ("Kelsey Hightower", 1981, "Google/Cloud engineer"),
    ("Kris Nova", 1990, "tech engineer"),
    ("Joe Beda", 1976, "Kubernetes creator"),
    ("Brendan Burns", None, "Kubernetes creator"),
    ("Craig McLuckie", None, "Kubernetes creator"),
    ("Brian Grant", None, "Kubernetes contributor"),
    ("Tim Hockin", None, "Kubernetes contributor"),
    ("Daniel Smith", None, "Kubernetes contributor"),
    ("Clayton Coleman", None, "Kubernetes contributor"),
    ("David Oppenheimer", None, "Kubernetes contributor"),
    ("Brendan Gregg", 1972, "Netflix/BPF engineer"),
    ("Adrian Cockcroft", 1957, "Netflix engineer"),
    ("Cory Watson", None, "Netflix engineer"),
    ("Josh Evans", None, "Netflix engineer"),
    ("Amjith Ramanan", None, "tech engineer"),
    ("Roshan Sivakumar", None, "tech engineer"),
]

# Wikipedia categories to scrape for additional candidates
WIKI_CATEGORIES = [
    "American computer scientists",
    "American software engineers",
    "American technology company founders",
    "American internet entrepreneurs",
    "British computer scientists",
    "British software engineers",
    "Indian computer scientists",
    "Canadian computer scientists",
    "German computer scientists",
    "French computer scientists",
    "Israeli computer scientists",
    "Japanese computer scientists",
    "Chinese computer scientists",
    "Russian computer scientists",
    "Artificial intelligence researchers",
    "Machine learning researchers",
    "Natural language processing researchers",
    "Programming language designers",
    "Open-source software advocates",
    "Free software programmers",
    "Video game developers",
    "Video game programmers",
    "Web developers",
    "American inventors",
    "Electrical engineers",
    "Computer engineers",
    "Cryptographers",
    "Blockchain people",
    "American businesspeople in technology",
    "American chief technology officers",
    "Silicon Valley businesspeople",
]


def wiki_category_members(category: str, limit: int = 500) -> list[dict]:
    """Fetch pages from a Wikipedia category, including birth year where available."""
    members = []
    cmcontinue = None
    while len(members) < limit:
        params = {
            "action": "query",
            "list": "categorymembers",
            "cmtitle": f"Category:{category}",
            "cmtype": "page",
            "cmlimit": "50",
            "format": "json",
        }
        if cmcontinue:
            params["cmcontinue"] = cmcontinue
        url = f"{WIKI_API}?{urllib.parse.urlencode(params)}"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "trajectory-research/0.1"})
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read())
        except Exception as e:
            print(f"  Wiki API error for {category}: {e}")
            break
        for m in data.get("query", {}).get("categorymembers", []):
            title = m.get("title", "")
            # Skip non-person pages
            if any(x in title for x in ["List of", "Category:", "Template:", "Wikipedia:", "Portal:", "Help:", "Category:", "Draft:"]):
                continue
            members.append({"name": title, "source": f"wiki:{category}"})
        if "continue" in data:
            cmcontinue = data["continue"]["cmcontinue"]
        else:
            break
        time.sleep(0.5)
    return members


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--existing", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--batches-dir", required=True)
    parser.add_argument("--batch-size", type=int, default=12)
    parser.add_argument("--limit", type=int, default=1200)
    parser.add_argument("--scrape-wiki", action="store_true", help="Scrape Wikipedia categories for more candidates")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)

    # Load existing names
    existing_names: set[str] = set()
    with open(args.existing, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            existing_names.add(row["name"].casefold().strip())

    candidates: list[dict] = []

    # Add curated candidates
    seen_names: set[str] = set()
    for name, birth_year, hint in CURATED:
        key = name.casefold().strip()
        if key in existing_names or key in seen_names:
            continue
        seen_names.add(key)
        candidates.append({
            "name": name,
            "birth_year": birth_year if birth_year else "",
            "occupation": hint,
            "country_name": "",
            "gender": "",
            "wikipedia_languages": "",
            "hpi": "",
            "source_record_url": f"https://en.wikipedia.org/wiki/{name.replace(' ', '_')}",
            "selection_note": f"Curated: {hint}",
        })

    print(f"Curated candidates (after dedup): {len(candidates)}")

    # Optionally scrape Wikipedia categories
    if args.scrape_wiki:
        for cat in WIKI_CATEGORIES:
            print(f"Scraping Category:{cat}...")
            members = wiki_category_members(cat, limit=200)
            for m in members:
                key = m["name"].casefold().strip()
                if key in existing_names or key in seen_names:
                    continue
                seen_names.add(key)
                candidates.append({
                    "name": m["name"],
                    "birth_year": "",
                    "occupation": cat,
                    "country_name": "",
                    "gender": "",
                    "wikipedia_languages": "",
                    "hpi": "",
                    "source_record_url": f"https://en.wikipedia.org/wiki/{m['name'].replace(' ', '_')}",
                    "selection_note": f"Wikipedia category: {cat}",
                })
            print(f"  Total so far: {len(candidates)}")
        print(f"Total after wiki scraping: {len(candidates)}")

    # Shuffle and limit
    random.shuffle(candidates)
    selected = candidates[: args.limit]

    print(f"Selected: {len(selected)}")

    # Write full CSV
    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "candidate_rank", "candidate_id", "name", "birth_year", "occupation",
        "country_name", "gender", "wikipedia_languages", "hpi",
        "source_record_url", "milestone_by_26_status", "research_status",
        "selection_note",
    ]
    with output.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for i, r in enumerate(selected, 1):
            cid = f"fe-candidate-{i:04d}-{r['name'].lower().replace(' ', '-').replace('--', '-')}"
            writer.writerow({
                "candidate_rank": i,
                "candidate_id": cid,
                "name": r["name"],
                "birth_year": r["birth_year"],
                "occupation": r["occupation"],
                "country_name": r["country_name"],
                "gender": r["gender"],
                "wikipedia_languages": r["wikipedia_languages"],
                "hpi": r["hpi"],
                "source_record_url": r["source_record_url"],
                "milestone_by_26_status": "unresearched",
                "research_status": "unverified_candidate",
                "selection_note": r["selection_note"],
            })

    # Write batches
    batches_dir = pathlib.Path(args.batches_dir)
    batches_dir.mkdir(parents=True, exist_ok=True)
    n_batches = (len(selected) + args.batch_size - 1) // args.batch_size
    for b in range(n_batches):
        chunk = selected[b * args.batch_size : (b + 1) * args.batch_size]
        bp = batches_dir / f"batch_fe_{b + 1:03d}.csv"
        with bp.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            for i, r in enumerate(chunk, 1):
                cid = f"fe-{b + 1:03d}-{i:02d}-{r['name'].lower().replace(' ', '-')}"
                writer.writerow({
                    "candidate_rank": i,
                    "candidate_id": cid,
                    "name": r["name"],
                    "birth_year": r["birth_year"],
                    "occupation": r["occupation"],
                    "country_name": r["country_name"],
                    "gender": r["gender"],
                    "wikipedia_languages": r["wikipedia_languages"],
                    "hpi": r["hpi"],
                    "source_record_url": r["source_record_url"],
                    "milestone_by_26_status": "unresearched",
                    "research_status": "unverified_candidate",
                    "selection_note": r["selection_note"],
                })
    print(f"Wrote {n_batches} batches to {batches_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
